version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: plotbook_db
    environment:
      POSTGRES_USER: plotbook_user
      POSTGRES_PASSWORD: plotbook_password
      POSTGRES_DB: plotbook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 